image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r test-lint-requirements.txt
  - pip install -e treepackage

test-job:
  stage: test
  script:
    - python -m unittest

lint-job:
  stage: test
  script:
    - flake8 client server test treepackage
