variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test
  - build

.before_script_template: &backend
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r test-lint-requirements.txt
    - pip install -e treepackage

test_backend:
  stage: test
  image: python:latest
  <<: *backend
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - python -m unittest

lint_backend:
  stage: test
  image: python:latest
  <<: *backend
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - flake8 client servpackage test treepackage

build_frontend:
  stage: build
  image: node
  cache:
    key:
      files:
        - client/frontend/package-lock.json
    paths:
      - client/frontend/node_modules
  script:
    - npm config set registry http://registry.npmjs.eu
    - cd client/frontend
    - npm install
    - npm run build
