version: '3'

services:
  mysql:
    image: mysql
    secrets:
      - db-password
    environment:
      MYSQL_DATABASE: testapp
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password

    ports:
      - "3308:3306"

secrets:
  db-password:
    file: password
