CREATE DATABASE IF NOT EXISTS db;
USE db;
CREATE TABLE IF NOT EXISTS reports (
    id INT UNSIGNED AUTO_INCREMENT primary key,
    environment TEXT,
    tree_json VARCHAR(5000),
    time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
