CREATE DATABASE IF NOT EXISTS db;
USE db;
DROP TABLE IF EXISTS reports;

CREATE TABLE reports (
    id INT UNSIGNED AUTO_INCREMENT primary key,
    environment VARCHAR(255) NOT NULL,
    tree_json MEDIUMTEXT NOT NULL,
    time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
